export const {
  PAYLOAD_SECRET = '',
  DATABASE_URI = '',
  NEXT_PUBLIC_WEB_URL = 'http://localhost:4321',
  ADMIN_URL = 'http://localhost:3000',
  R2_ACCOUNT_ID = '',
  R2_ACCESS_KEY_ID = '',
  R2_SECRET_ACCESS_KEY = '',
  R2_BUCKET = '',
} = process.env
